SettingsScreen As screen:
    Fill: =Color.White
    LoadingSpinnerColor: =App.Theme.Colors.Primary
    OnVisible: |
        =//Reset(menu_3);
        //UpdateContext({varspinner:true});
        Set(varMenuID,9);
        Reset(Gallery5_22);
        Set(varNewScore,First(Filter(Registrations_Dvs,LoginName=varlgname)).Scores);

    MainContainer_6 As groupContainer.verticalAutoLayoutContainer:
        DropShadow: =DropShadow.Light
        Fill: =RGBA(245, 245, 245, 1)
        Height: =Parent.Height
        LayoutAlignItems: =LayoutAlignItems.Stretch
        LayoutDirection: =LayoutDirection.Vertical
        LayoutGap: =1
        LayoutMode: =LayoutMode.Auto
        RadiusBottomLeft: =4
        RadiusBottomRight: =4
        RadiusTopLeft: =4
        RadiusTopRight: =4
        Width: =Parent.Width
        ZIndex: =1

        TopNavContainer_6 As groupContainer.horizontalAutoLayoutContainer:
            AlignInContainer: =AlignInContainer.SetByContainer
            DropShadow: =DropShadow.Light
            Fill: =RGBA(255, 255, 255, 1)
            FillPortions: =0
            Height: =60
            LayoutAlignItems: =LayoutAlignItems.Center
            LayoutGap: =20
            LayoutJustifyContent: =LayoutJustifyContent.SpaceBetween
            LayoutMinHeight: =100
            LayoutMinWidth: =250
            LayoutMode: =LayoutMode.Auto
            LayoutWrap: =true
            PaddingLeft: =10
            PaddingRight: =10
            RadiusBottomLeft: =1
            RadiusBottomRight: =1
            RadiusTopLeft: =1
            RadiusTopRight: =1
            ZIndex: =2

            TopMenu_6 As groupContainer.manualLayoutContainer:
                AlignInContainer: =AlignInContainer.SetByContainer
                Height: =Parent.Height
                LayoutMinHeight: =100
                LayoutMinWidth: =250
                RadiusBottomLeft: =4
                RadiusBottomRight: =4
                RadiusTopLeft: =4
                RadiusTopRight: =4
                Width: =Parent.Width
                ZIndex: =1

                "Gallery5_22 As gallery.'BrowseLayout_Horizontal_TwoTextOneImageVariant_ver5.0'":
                    BorderColor: =App.Theme.Colors.Darker40
                    DelayItemLoading: =true
                    Height: =60
                    Items: |-
                        =Table( { Value: "Home" }, { Value: "What is SAIL?" },{ Value: "Lore" } )
                    LoadingSpinner: =LoadingSpinner.Data
                    TemplatePadding: =0
                    TemplateSize: =148
                    Width: =447
                    X: =729
                    ZIndex: =1

                    ButtonCanvas3_12 As Button:
                        Align: =Align.Justify
                        Appearance: ='ButtonCanvas.Appearance'.Subtle
                        BasePaletteColor: =RGBA(246, 142, 104, 1)
                        DisplayMode: =DisplayMode.Edit
                        FontColor: =
                        Height: =29
                        IconStyle: ='ButtonCanvas.IconStyle'.Outline
                        OnSelect: |-
                            =If(ThisItem.Value="Home",Navigate(LandingPageOctalysis));
                            If(ThisItem.Value="Lore",Navigate(IntroScreenWhatIsSail));
                        Text: =ThisItem.Value
                        Width: =131
                        X: =10
                        Y: =15
                        ZIndex: =1

                    Rectangle1_29 As rectangle:
                        BorderColor: =App.Theme.Colors.Darker40
                        Fill: =App.Theme.Colors.Primary
                        Height: =2
                        Visible: =ThisItem.IsSelected
                        Width: =120
                        X: =15
                        Y: =58
                        ZIndex: =2

                Image5_9 As image:
                    BorderColor: =App.Theme.Colors.Darker40
                    DisabledBorderColor: =RGBA(166, 166, 166, 1)
                    DisabledFill: =RGBA(244, 244, 244, 1)
                    Height: =50
                    Image: =Micrsooft
                    X: =3
                    Y: =5
                    ZIndex: =1

                ButtonCanvas1_11 As Button:
                    BasePaletteColor: =RGBA(5, 102, 178, 1)
                    DisplayMode: =DisplayMode.Edit
                    Height: =32
                    Icon: ="DocumentBulletList"
                    OnSelect: =Navigate(PromptLibraryScreen)
                    PaddingRight: =0
                    Text: ="Prompt Library"
                    Width: =150
                    X: =1176
                    Y: =14
                    ZIndex: =2

                Image7_11 As image:
                    BorderColor: =App.Theme.Colors.Darker40
                    DisabledBorderColor: =RGBA(166, 166, 166, 1)
                    DisabledFill: =RGBA(244, 244, 244, 1)
                    Height: =50
                    Image: =varUserAvtar
                    RadiusBottomLeft: =50
                    RadiusBottomRight: =50
                    RadiusTopLeft: =50
                    RadiusTopRight: =50
                    Width: =50
                    X: =360
                    Y: =5
                    ZIndex: =3

                TextCanvas1_22 As Text:
                    Align: ='TextCanvas.Align'.Start
                    DisplayMode: =DisplayMode.Edit
                    Font: =Font.'Segoe UI'
                    FontColor: =RGBA(0, 0, 0, 1)
                    Height: =30
                    Size: =14
                    Text: =varlgname
                    Weight: ='TextCanvas.Weight'.Semibold
                    Width: =144
                    Wrap: =true
                    X: =421
                    Y: =14
                    ZIndex: =4

        BottomContainer_6 As groupContainer.horizontalAutoLayoutContainer:
            AlignInContainer: =AlignInContainer.SetByContainer
            Fill: =RGBA(245, 245, 245, 1)
            LayoutAlignItems: =LayoutAlignItems.Stretch
            LayoutGap: =1
            LayoutMinHeight: =100
            LayoutMinWidth: =200
            LayoutMode: =LayoutMode.Auto
            LayoutWrap: =true
            PaddingBottom: =2
            PaddingLeft: =2
            PaddingRight: =2
            PaddingTop: =2
            RadiusBottomLeft: =4
            RadiusBottomRight: =4
            RadiusTopLeft: =4
            RadiusTopRight: =4
            ZIndex: =3

            LeftNavContainer_6 As groupContainer.verticalAutoLayoutContainer:
                AlignInContainer: =AlignInContainer.SetByContainer
                DropShadow: =DropShadow.Light
                Fill: =RGBA(255, 255, 255, 1)
                LayoutDirection: =LayoutDirection.Vertical
                LayoutMinHeight: =100
                LayoutMinWidth: =230
                LayoutMode: =LayoutMode.Auto
                RadiusBottomLeft: =1
                RadiusBottomRight: =1
                RadiusTopLeft: =1
                RadiusTopRight: =1
                ZIndex: =4

                menu_8 As menu:
                    LayoutMinWidth: =640
                    score: =varNewScore
                    ScreenChallenge: =ChallengeScreen
                    ScreenFeedback: =FeedbackScreen
                    ScreenLB: =SettingsScreen
                    ScreenNavHome: =HomeScreen
                    ScreenNavPrompt: =PromptLibraryScreen
                    ScreenSquad: =SquadScreen
                    varID: =9
                    VarMenuDefaultVal: |-
                        =//vardefault
                        //{ ID:2,Icon:Icon.Home ,Value: "Home" }
                        
                        //{ ID:1,Icon:"" ,Value: "Discover" }, { ID:2,Icon:Icon.Home ,Value: "Home" }, { ID:3,Icon:Icon.ListScrollWatchlist ,Value: "Prompt Library" },{ ID:4,Icon:"" ,Value: "Play" } ,{ ID:5,Icon:Icon.Signal ,Value: "Challenges" },{ ID:6,Icon:Icon.OptionsList ,Value: "Leader Boards" },{ ID:7,Icon:Icon.EmojiSmile ,Value: "Squad" },{ ID:8,Icon:"" ,Value: "Adjust" },{ ID:9,Icon:Icon.Settings ,Value: "Settings" },{ ID:10,Icon:Icon.Post ,Value: "Feedback" }
                        
                        Switch(menu_8.varID,
                        2, { ID:2,Icon:Icon.Home ,Value: "Home" }, 
                        3, { ID:3,Icon:Icon.ListScrollWatchlist ,Value: "Prompt Library" }
                        )

            CommonContainer_6 As groupContainer.verticalAutoLayoutContainer:
                AlignInContainer: =AlignInContainer.SetByContainer
                DropShadow: =DropShadow.Light
                FillPortions: =7
                LayoutDirection: =LayoutDirection.Vertical
                LayoutMinHeight: =100
                LayoutMinWidth: =250
                LayoutMode: =LayoutMode.Auto
                RadiusBottomLeft: =1
                RadiusBottomRight: =1
                RadiusTopLeft: =1
                RadiusTopRight: =1
                ZIndex: =5

                Container3_6 As groupContainer.horizontalAutoLayoutContainer:
                    DropShadow: =DropShadow.Light
                    FillPortions: =0
                    Height: =60
                    LayoutMinHeight: =20
                    LayoutMinWidth: =250
                    LayoutMode: =LayoutMode.Auto
                    RadiusBottomLeft: =4
                    RadiusBottomRight: =4
                    RadiusTopLeft: =4
                    RadiusTopRight: =4
                    ZIndex: =1

                    "Gallery5_23 As gallery.'BrowseLayout_Horizontal_TwoTextOneImageVariant_ver5.0'":
                        AlignInContainer: =AlignInContainer.Center
                        BorderColor: =App.Theme.Colors.Darker40
                        Default: |-
                            ={ ID:1,Value: "Home" }
                        DelayItemLoading: =true
                        Fill: =RGBA(255, 255, 255, 1)
                        Height: =60
                        Items: |-
                            =Table( { ID:1,Value: "Home" }, { ID:2,Value: "Rewards" })
                        LayoutMinHeight: =287
                        LayoutMinWidth: =320
                        TemplatePadding: =0
                        TemplateSize: =148
                        Visible: =If(menu_8.SelectedItem.ID=6,true,false)
                        Width: =447
                        X: =729
                        ZIndex: =1

                        ButtonCanvas3_13 As Button:
                            Align: =Align.Justify
                            Appearance: ='ButtonCanvas.Appearance'.Subtle
                            BasePaletteColor: =RGBA(246, 142, 104, 1)
                            DisplayMode: =DisplayMode.Edit
                            FontColor: =
                            Height: =29
                            IconStyle: ='ButtonCanvas.IconStyle'.Outline
                            OnSelect: =//If(ThisItem.Value="Home",Navigate(LandingPageOctalysis));
                            Text: =ThisItem.Value
                            Width: =131
                            X: =10
                            Y: =15
                            ZIndex: =1

                        Rectangle1_30 As rectangle:
                            BorderColor: =App.Theme.Colors.Darker40
                            Fill: =App.Theme.Colors.Primary
                            Height: =2
                            Visible: =ThisItem.IsSelected
                            Width: =120
                            X: =15
                            Y: =55
                            ZIndex: =2

                Container20_2 As groupContainer.horizontalAutoLayoutContainer:
                    DropShadow: =DropShadow.Light
                    LayoutMinHeight: =100
                    LayoutMinWidth: =250
                    LayoutMode: =LayoutMode.Auto
                    RadiusBottomLeft: =4
                    RadiusBottomRight: =4
                    RadiusTopLeft: =4
                    RadiusTopRight: =4
                    ZIndex: =2

                    Container21_2 As groupContainer.verticalAutoLayoutContainer:
                        DropShadow: =DropShadow.Light
                        FillPortions: =0
                        LayoutDirection: =LayoutDirection.Vertical
                        LayoutMinHeight: =100
                        LayoutMinWidth: =350
                        LayoutMode: =LayoutMode.Auto
                        RadiusBottomLeft: =4
                        RadiusBottomRight: =4
                        RadiusTopLeft: =4
                        RadiusTopRight: =4
                        Width: =850
                        ZIndex: =1

                    Container22_2 As groupContainer.verticalAutoLayoutContainer:
                        DropShadow: =DropShadow.Light
                        LayoutDirection: =LayoutDirection.Vertical
                        LayoutMinHeight: =100
                        LayoutMinWidth: =250
                        LayoutMode: =LayoutMode.Auto
                        RadiusBottomLeft: =4
                        RadiusBottomRight: =4
                        RadiusTopLeft: =4
                        RadiusTopRight: =4
                        ZIndex: =2

    ContainerSpinner_5 As groupContainer:
        DropShadow: =DropShadow.Light
        Height: =768
        RadiusBottomLeft: =4
        RadiusBottomRight: =4
        RadiusTopLeft: =4
        RadiusTopRight: =4
        Visible: =varspinner
        Width: =1366
        ZIndex: =25

        Timer1_7 As timer:
            AutoStart: =true
            Duration: =3000
            Fill: =RGBA(56, 96, 178, 1)
            HoverColor: =RGBA(255, 255, 255, 1)
            HoverFill: =ColorFade(RGBA(56, 96, 178, 1), -20%)
            OnTimerEnd: |-
                =UpdateContext({varspinner:false})
            Visible: =false
            X: =118
            Y: =699
            ZIndex: =1

        Shadowed_Bck_14 As rectangle:
            BorderColor: =RGBA(0, 18, 107, 1)
            Fill: =RGBA(0, 0, 0, 0.6)
            Height: =768
            Visible: =varspinner
            Width: =1366
            ZIndex: =2

        Spinner_9 As image:
            BorderColor: =RGBA(0, 18, 107, 1)
            DisabledBorderColor: =RGBA(166, 166, 166, 1)
            DisabledFill: =RGBA(244, 244, 244, 1)
            Image: |
                ="data:image/svg+xml;utf8, " & EncodeUrl("<svg xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' style='margin: auto; background: none; display: block; shape-rendering: auto;' width='200px' height='200px' viewBox='0 0 100 100' preserveAspectRatio='xMidYMid'>
                <circle cx='50' cy='50' r='32' stroke-width='8' stroke='#00aab4' stroke-dasharray='50.26548245743669 50.26548245743669' fill='none' stroke-linecap='round'>
                  <animateTransform attributeName='transform' type='rotate' dur='1s' repeatCount='indefinite' keyTimes='0;1' values='0 50 50;360 50 50'></animateTransform>
                </circle>
                <circle cx='50' cy='50' r='23' stroke-width='8' stroke='#f4f4f4' stroke-dasharray='36.12831551628262 36.12831551628262' stroke-dashoffset='36.12831551628262' fill='none' stroke-linecap='round'>
                  <animateTransform attributeName='transform' type='rotate' dur='1s' repeatCount='indefinite' keyTimes='0;1' values='0 50 50;-360 50 50'></animateTransform>
                </circle>
                <!-- [ldio] generated by https://loading.io/ --></svg>")
            Visible: =varspinner
            X: =704
            Y: =341
            ZIndex: =3

